version: "3"

services:
  postgres:
    container_name: "scraping-postgres"
    image: postgres:12
    ports:
      - "5432:5432"
    volumes:
      - ~/apps/postgres:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=1234
      - POSTGRES_USER=guijas
      - POSTGRES_DB=scraping
